[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
]

[contracts]
ERC721MetadataUpdate = ["src/erc4906/presets/ERC721MetadataUpdate.cairo"]

